"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:07:35.387749
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_records',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('ci_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requester', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_change_records_ci_id'), 'change_records', ['ci_id'], unique=False)
    op.create_index(op.f('ix_change_records_status'), 'change_records', ['status'], unique=False)
    op.create_table('ci_relations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('source_ci_id', sa.String(length=64), nullable=False),
    sa.Column('target_ci_id', sa.String(length=64), nullable=False),
    sa.Column('relation_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ci_relations_relation_type'), 'ci_relations', ['relation_type'], unique=False)
    op.create_index(op.f('ix_ci_relations_source_ci_id'), 'ci_relations', ['source_ci_id'], unique=False)
    op.create_index(op.f('ix_ci_relations_status'), 'ci_relations', ['status'], unique=False)
    op.create_index(op.f('ix_ci_relations_target_ci_id'), 'ci_relations', ['target_ci_id'], unique=False)
    op.create_table('cis',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('ci_type', sa.String(length=16), nullable=False),
    sa.Column('environment', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=80), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cis_ci_type'), 'cis', ['ci_type'], unique=False)
    op.create_index(op.f('ix_cis_environment'), 'cis', ['environment'], unique=False)
    op.create_index(op.f('ix_cis_name'), 'cis', ['name'], unique=True)
    op.create_index(op.f('ix_cis_status'), 'cis', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cis_status'), table_name='cis')
    op.drop_index(op.f('ix_cis_name'), table_name='cis')
    op.drop_index(op.f('ix_cis_environment'), table_name='cis')
    op.drop_index(op.f('ix_cis_ci_type'), table_name='cis')
    op.drop_table('cis')
    op.drop_index(op.f('ix_ci_relations_target_ci_id'), table_name='ci_relations')
    op.drop_index(op.f('ix_ci_relations_status'), table_name='ci_relations')
    op.drop_index(op.f('ix_ci_relations_source_ci_id'), table_name='ci_relations')
    op.drop_index(op.f('ix_ci_relations_relation_type'), table_name='ci_relations')
    op.drop_table('ci_relations')
    op.drop_index(op.f('ix_change_records_status'), table_name='change_records')
    op.drop_index(op.f('ix_change_records_ci_id'), table_name='change_records')
    op.drop_table('change_records')
    # ### end Alembic commands ###
